title: Hannah Hennighausen's academic site 
logo: /assets/img/thememountainsbig.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
